import { CalendarCheck2, Check, Clock3, Pencil } from "lucide-react";
import { ConfirmAction } from "@/components/ui/ConfirmAction";
import { CustomSelect } from "@/components/ui/CustomSelect";
import { DateTimePicker } from "@/components/ui/DateTimePicker";
import { Modal } from "@/components/ui/Modal";
import type { calendars, tasks } from "@/db/schema";
import { deleteTask, scheduleTask, toggleTask, updateTask } from "../actions";

type TaskItem = typeof tasks.$inferSelect;
type CalendarItem = typeof calendars.$inferSelect;
type DayPlan = { date: Date; key: string; tasks: TaskItem[] };

const dayKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const dateInput = (date: Date | null) => date ? new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16) : "";

function PlanTaskCard({ task, calendars: calendarList }: { task: TaskItem; calendars: CalendarItem[] }) {
  const calendar = calendarList.find((item) => item.id === task.calendarId);
  const name = calendarList.find((item) => item.id === task.calendarId)?.name ?? "Без календаря";
  return <article className="rounded-xl border border-[#e8e9f1] border-l-[3px] bg-white p-3 shadow-sm" style={{ borderLeftColor: calendar?.color ?? "#a3a5b8" }}>
    <div className="flex items-start gap-2.5">
      <form action={toggleTask} className="pt-0.5"><input type="hidden" name="id" value={task.id}/><input type="hidden" name="completed" value="true"/><button aria-label="Отметить выполненной" className="grid h-[18px] w-[18px] place-items-center rounded-md border border-[#c7cad7] text-transparent transition hover:border-[#625cf0] hover:text-[#625cf0]"><Check aria-hidden="true" size={12}/></button></form>
      <div className="min-w-0 flex-1"><h3 className="break-words text-xs font-semibold leading-5 text-[#34364a]">{task.title}</h3>{task.dueAt && <p className="mt-1 inline-flex items-center gap-1 text-[10px] tabular-nums text-[#85879a]"><Clock3 aria-hidden="true" size={11}/>{task.dueAt.toLocaleTimeString("ru-RU", { hour: "2-digit", minute: "2-digit" })}</p>}<p className="mt-1 truncate text-[10px] text-[#989aaa]">{name}</p></div>
      <div className="flex shrink-0 items-center gap-0.5"><Modal title="Изменить задачу" description="Обновите срок или календарь задачи." trigger={<Pencil aria-hidden="true" size={13}/>} triggerClassName="grid h-7 w-7 place-items-center rounded-lg text-[#8d8fa0] transition hover:bg-[#f0efff] hover:text-[#514be0]"><form action={updateTask} className="grid gap-3"><input type="hidden" name="id" value={task.id}/><input type="hidden" name="title" value={task.title}/><input type="hidden" name="description" value={task.description ?? ""}/><label className="text-xs font-medium text-[#656779]">Дата и время<DateTimePicker name="dueAt" mode="datetime" defaultValue={dateInput(task.dueAt)} placeholder="Выбрать дату"/></label><label className="text-xs font-medium text-[#656779]">Календарь<CustomSelect name="calendarId" defaultValue={task.calendarId ?? ""} options={[{ value: "", label: "Без календаря" }, ...calendarList.map((item) => ({ value: item.id, label: item.name, color: item.color }))]}/></label><button className="rounded-xl bg-[#625cf0] px-4 py-2.5 text-xs font-semibold text-white">Сохранить план</button></form></Modal><ConfirmAction title="Удалить задачу" description="Задача будет удалена без возможности восстановления." action={deleteTask} fields={{ id: task.id}}/></div>
    </div>
  </article>;
}

export function TaskPlanBoard({ days, backlog, calendars: calendarList, today, weekStart, weekLabel }: { days: DayPlan[]; backlog: TaskItem[]; calendars: CalendarItem[]; today: string; weekStart: string; weekLabel: string }) {
  const peak = Math.max(1, ...days.map((day) => day.tasks.length));
  return <div className="mt-5 space-y-5">
    <section className="rounded-2xl border border-[#dedfff] bg-gradient-to-br from-[#f5f4ff] via-white to-[#effbff] p-4 sm:p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#7771d9]">План недели</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-[#303247]">{weekLabel}</h2></div><p className="text-xs text-[#77798d]">{days.reduce((sum, day) => sum + day.tasks.length, 0)} задач распределено · {backlog.length} требуют планирования</p></div><div className="mt-4 grid h-8 grid-cols-7 items-end gap-2" aria-label="Распределение задач по дням">{days.map((day) => <div key={day.key} title={`${day.tasks.length} задач`} className="flex h-full items-end"><span className="w-full rounded-t-md bg-gradient-to-t from-[#5e58e8] to-[#9b97ff] transition-all" style={{ height: `${day.tasks.length ? Math.max(20, day.tasks.length / peak * 100) : 8}%`, opacity: day.tasks.length ? 1 : 0.24 }}/></div>)}</div><div className="mt-2 grid grid-cols-7 gap-2 text-center text-[9px] text-[#85879a]">{days.map((day) => <span key={day.key}>{new Intl.DateTimeFormat("ru-RU", { weekday: "short" }).format(day.date)}</span>)}</div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{days.map((day) => { const isToday = day.key === today; return <article key={day.key} className={`min-h-36 rounded-2xl border p-3 ${isToday ? "border-[#aaa6ff] bg-[#f9f8ff] shadow-sm shadow-[#625cf0]/10" : "border-[#e4e5ed] bg-[#f8f9fc]"}`}><header className="mb-3 flex items-center justify-between gap-2"><div><h3 className={`text-xs font-bold capitalize ${isToday ? "text-[#514be0]" : "text-[#505267]"}`}>{new Intl.DateTimeFormat("ru-RU", { weekday: "long" }).format(day.date)}</h3><p className="mt-0.5 text-[10px] text-[#898b9d]">{new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long" }).format(day.date)}</p></div><span className={`rounded-lg px-2 py-1 text-[10px] font-semibold ${day.tasks.length ? "bg-[#e9e8ff] text-[#514be0]" : "bg-white text-[#9698a7]"}`}>{day.tasks.length}</span></header><div className="space-y-2">{day.tasks.length ? day.tasks.map((task) => <PlanTaskCard key={task.id} task={task} calendars={calendarList}/>) : <p className="rounded-xl border border-dashed border-[#dfe0e9] bg-white/70 px-3 py-4 text-center text-[10px] text-[#a0a2b1]">Свободный день</p>}</div></article>; })}</section>

    <section className="overflow-hidden rounded-2xl border border-[#e4d8bb] bg-[#fffdf8]"><header className="flex flex-wrap items-center justify-between gap-2 border-b border-[#f0e8d9] px-4 py-3.5"><div><h2 className="text-sm font-bold text-[#514b3e]">Нужно распределить</h2><p className="mt-1 text-[10px] text-[#918873]">Просроченные и задачи без даты. Назначьте день и календарь.</p></div><span className="rounded-lg bg-[#fff1d5] px-2.5 py-1 text-[10px] font-bold text-[#996400]">{backlog.length}</span></header>{backlog.length ? <div className="divide-y divide-[#f0e8d9]">{backlog.map((task) => { const dueDay = task.dueAt ? dayKey(task.dueAt) : ""; const overdue = Boolean(dueDay && dueDay < today); return <article key={task.id} className="grid gap-3 px-4 py-3.5 md:grid-cols-[minmax(0,1fr)_minmax(260px,.9fr)] md:items-center"><div className="flex min-w-0 items-start gap-2.5"><form action={toggleTask} className="pt-0.5"><input type="hidden" name="id" value={task.id}/><input type="hidden" name="completed" value="true"/><button aria-label="Отметить выполненной" className="grid h-[18px] w-[18px] place-items-center rounded-md border border-[#c7cad7] text-transparent transition hover:border-[#625cf0] hover:text-[#625cf0]"><Check aria-hidden="true" size={12}/></button></form><div className="min-w-0"><p className="break-words text-xs font-semibold text-[#454659]">{task.title}</p><p className={`mt-1 text-[10px] ${overdue ? "font-semibold text-[#c94f39]" : "text-[#9294a3]"}`}>{overdue ? `Просрочена · ${task.dueAt!.toLocaleDateString("ru-RU", { day: "numeric", month: "short" })}` : task.dueAt ? `Срок вне недели · ${task.dueAt.toLocaleDateString("ru-RU", { day: "numeric", month: "short" })}` : "Без даты"}</p></div></div><form action={scheduleTask} className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)_auto] items-end gap-2"><input type="hidden" name="id" value={task.id}/><input type="hidden" name="week" value={weekStart}/><label className="min-w-0 text-[9px] font-semibold text-[#858697]">День<DateTimePicker name="date" mode="date" placeholder="Выбрать день"/></label><label className="min-w-0 text-[9px] font-semibold text-[#858697]">Календарь<CustomSelect name="calendarId" defaultValue={task.calendarId ?? ""} options={[{ value: "", label: "Без календаря" }, ...calendarList.map((calendar) => ({ value: calendar.id, label: calendar.name, color: calendar.color }))]}/></label><button aria-label="Запланировать задачу" title="Запланировать" className="grid h-10 w-10 place-items-center rounded-xl bg-[#625cf0] text-white transition hover:bg-[#514be0]"><CalendarCheck2 aria-hidden="true" size={17}/></button></form></article>; })}</div> : <p className="px-4 py-8 text-center text-xs text-[#828496]">Все задачи распределены по плану.</p>}</section>
  </div>;
}
