import Link from "next/link";
import { ArrowDownLeft, ArrowUpRight, Pencil, Plus } from "lucide-react";
import { and, asc, desc, eq, gte, lte } from "drizzle-orm";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { ModuleShell } from "@/components/app/ModuleShell";
import { CustomSelect } from "@/components/ui/CustomSelect";
import { Modal } from "@/components/ui/Modal";
import { ConfirmAction } from "@/components/ui/ConfirmAction";
import { authOptions } from "@/auth";
import { db } from "@/db";
import { financialCategories, financialTransactions } from "@/db/schema";
import { createFinancialCategory, createTransaction, deleteFinancialCategory, deleteTransaction, updateFinancialCategory } from "../modules/actions";
import { TransactionForm } from "./TransactionForm";

type Range = "week" | "month" | "year" | "all";
type TypeFilter = "all" | "income" | "expense";
type Params = Promise<{ error?: string; created?: string; range?: string; type?: string; category?: string; categoryCreated?: string; categoryUpdated?: string; categoryDeleted?: string }>;
const dayKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const money = (amount: number) => new Intl.NumberFormat("ru-RU", { style: "currency", currency: "RUB", maximumFractionDigits: 0 }).format(amount);
const rangeNames: Record<Range, string> = { week: "Эта неделя", month: "Этот месяц", year: "Этот год", all: "Всё время" };

export default async function FinancePage({ searchParams }: { searchParams: Params }) {
  const session = await getServerSession(authOptions);
  if (!session?.user.id) redirect("/auth/login");
  const params = await searchParams;
  const now = new Date();
  const today = dayKey(now);
  const range: Range = params.range === "week" || params.range === "year" || params.range === "all" ? params.range : "month";
  const type: TypeFilter = params.type === "income" || params.type === "expense" ? params.type : "all";
  const monthStart = `${today.slice(0, 7)}-01`;
  const weekStart = dayKey(new Date(now.getFullYear(), now.getMonth(), now.getDate() - ((now.getDay() + 6) % 7)));
  const periodStart = range === "week" ? weekStart : range === "month" ? monthStart : range === "year" ? `${now.getFullYear()}-01-01` : "0001-01-01";
  const [categories, periodEntries] = await Promise.all([
    db.select().from(financialCategories).where(eq(financialCategories.userId, session.user.id)).orderBy(asc(financialCategories.type), asc(financialCategories.name)),
    db.select().from(financialTransactions).where(and(eq(financialTransactions.userId, session.user.id), gte(financialTransactions.occurredAt, periodStart), lte(financialTransactions.occurredAt, today))).orderBy(desc(financialTransactions.occurredAt), desc(financialTransactions.createdAt)),
  ]);
  const selectedCategoryId = categories.some((category) => category.id === params.category) ? params.category! : "";
  const selectedCategory = categories.find((category) => category.id === selectedCategoryId);
  const filteredEntries = periodEntries.filter((entry) => (type === "all" || entry.type === type) && (!selectedCategory || (entry.type === selectedCategory.type && entry.category === selectedCategory.name)));
  const income = filteredEntries.filter((entry) => entry.type === "income").reduce((sum, entry) => sum + Number(entry.amount), 0);
  const expenses = filteredEntries.filter((entry) => entry.type === "expense").reduce((sum, entry) => sum + Number(entry.amount), 0);
  const balance = income - expenses;
  const firstEntryDay = periodEntries.length ? [...periodEntries].sort((a, b) => a.occurredAt.localeCompare(b.occurredAt))[0].occurredAt : today;
  const elapsedDays = range === "week" ? Math.max(1, Math.floor((new Date(`${today}T12:00:00`).getTime() - new Date(`${weekStart}T12:00:00`).getTime()) / 86_400_000) + 1) : range === "all" ? Math.max(1, Math.floor((new Date(`${today}T12:00:00`).getTime() - new Date(`${firstEntryDay}T12:00:00`).getTime()) / 86_400_000) + 1) : range === "year" ? Math.max(1, Math.floor((new Date(`${today}T12:00:00`).getTime() - new Date(`${now.getFullYear()}-01-01T12:00:00`).getTime()) / 86_400_000) + 1) : now.getDate();
  const savingsRate = income ? Math.round((balance / income) * 100) : 0;

  const buckets: { label: string; start: string; end: string }[] = [];
  if (range === "week") {
    for (let i = 0; i < 7; i++) { const start = dayKey(new Date(now.getFullYear(), now.getMonth(), now.getDate() - ((now.getDay() + 6) % 7) + i)); const endDate = new Date(`${start}T12:00:00`); endDate.setDate(endDate.getDate() + 1); buckets.push({ label: new Intl.DateTimeFormat("ru-RU", { weekday: "short" }).format(new Date(`${start}T12:00:00`)).replace(".", ""), start, end: dayKey(endDate) }); }
  } else if (range === "month") {
    const count = Math.ceil(now.getDate() / 7);
    for (let i = 0; i < count; i++) { const start = `${today.slice(0, 7)}-${String(i * 7 + 1).padStart(2, "0")}`; const endDay = Math.min(i * 7 + 8, new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate() + 1); buckets.push({ label: `${i * 7 + 1}–${endDay - 1}`, start, end: `${today.slice(0, 7)}-${String(endDay).padStart(2, "0")}` }); }
  } else {
    const chartStart = range === "year" ? new Date(now.getFullYear(), 0, 1) : new Date(now.getFullYear(), now.getMonth() - 11, 1);
    for (let i = 0; i < 12; i++) { const startDate = new Date(chartStart.getFullYear(), chartStart.getMonth() + i, 1); const endDate = new Date(startDate.getFullYear(), startDate.getMonth() + 1, 1); buckets.push({ label: new Intl.DateTimeFormat("ru-RU", { month: "short" }).format(startDate).replace(".", ""), start: dayKey(startDate), end: dayKey(endDate) }); }
  }
  const chartValues = buckets.map((bucket) => ({ ...bucket, income: periodEntries.filter((entry) => entry.type === "income" && entry.occurredAt >= bucket.start && entry.occurredAt < bucket.end).reduce((sum, entry) => sum + Number(entry.amount), 0), expense: periodEntries.filter((entry) => entry.type === "expense" && entry.occurredAt >= bucket.start && entry.occurredAt < bucket.end).reduce((sum, entry) => sum + Number(entry.amount), 0) }));
  const chartMax = Math.max(1, ...chartValues.flatMap((bucket) => [bucket.income, bucket.expense]));
  const expenseGroups = new Map<string, number>();
  for (const entry of periodEntries) if (entry.type === "expense") expenseGroups.set(entry.category, (expenseGroups.get(entry.category) ?? 0) + Number(entry.amount));
  const expenseBreakdown = [...expenseGroups].map(([name, amount]) => ({ name, amount, color: categories.find((category) => category.type === "expense" && category.name === name)?.color ?? "#98a2b3" })).sort((a, b) => b.amount - a.amount).slice(0, 7);
  const recentEntries = filteredEntries.slice(0, 40);
  const preserved = (next: { range?: Range; type?: TypeFilter; category?: string }) => `/app/finance?range=${next.range ?? range}&type=${next.type ?? type}${(next.category ?? selectedCategoryId) ? `&category=${next.category ?? selectedCategoryId}` : ""}`;
  const errorMessage = params.error === "duplicate-category" ? "Категория с таким названием уже есть." : params.error === "category" ? "Проверьте название и цвет категории." : params.error ? "Проверьте сумму, тип операции, категорию и дату." : null;

  return <ModuleShell active="Финансы" userLabel={session.user.name ?? session.user.email ?? "Аккаунт"}>
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-semibold tracking-[.14em] text-[#898b9c]">ЛИЧНЫЙ БЮДЖЕТ</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em]">Финансы</h1><p className="mt-2 text-sm text-[#656779]">Движение денег, расходы по категориям и история операций.</p></div><Modal title="Новая операция" description="Добавьте доход или расход с категорией и датой." trigger={<><Plus aria-hidden="true" size={16}/><span>Добавить операцию</span></>}><TransactionForm action={createTransaction} categories={categories} defaultDate={today}/></Modal></header>

    <nav aria-label="Период аналитики" className="mt-6 flex flex-wrap gap-2">{(["week", "month", "year", "all"] as Range[]).map((value) => <Link key={value} href={preserved({ range: value })} aria-current={range === value ? "page" : undefined} className={`rounded-xl px-3.5 py-2 text-xs font-semibold transition ${range === value ? "bg-[#625cf0] text-white shadow-md shadow-[#625cf0]/20" : "border border-[#e1e2eb] bg-white text-[#626478] hover:border-[#bbb7ff] hover:text-[#514be0]"}`}>{rangeNames[value]}</Link>)}</nav>
    <form action="/app/finance" className="mt-3 flex flex-wrap items-center gap-2 rounded-2xl border border-[#e5e6ef] bg-white p-3"><input type="hidden" name="range" value={range}/><label className="sr-only" htmlFor="finance-type-filter">Тип операций</label><CustomSelect name="type" ariaLabel="Тип операций" defaultValue={type} className="min-w-36" options={[{ value: "all", label: "Все операции" }, { value: "income", label: "Доходы" }, { value: "expense", label: "Расходы" }]}/><label className="sr-only" htmlFor="finance-category-filter">Категория</label><CustomSelect name="category" ariaLabel="Категория" defaultValue={selectedCategoryId} className="min-w-44 flex-1" options={[{ value: "", label: "Все категории" }, ...categories.map((category) => ({ value: category.id, label: `${category.type === "income" ? "Доход · " : "Расход · "}${category.name}`, color: category.color }))]}/><button className="rounded-xl bg-[#f0efff] px-4 py-2.5 text-xs font-semibold text-[#514be0] hover:bg-[#e7e5ff]">Применить</button></form>

    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-2xl border border-[#ccebd9] bg-gradient-to-br from-[#f0fdf4] to-white p-4"><p className="text-xs font-medium text-[#528269]">Доходы · {rangeNames[range].toLowerCase()}</p><p className="mt-2 text-xl font-bold tracking-tight text-[#16824b]">{money(income)}</p></article><article className="rounded-2xl border border-[#f4d4cc] bg-gradient-to-br from-[#fff5f2] to-white p-4"><p className="text-xs font-medium text-[#a26759]">Расходы · {rangeNames[range].toLowerCase()}</p><p className="mt-2 text-xl font-bold tracking-tight text-[#c94f39]">{money(expenses)}</p></article><article className="rounded-2xl border border-[#d9dcf6] bg-gradient-to-br from-[#f3f4ff] to-white p-4"><p className="text-xs font-medium text-[#6868a4]">Остаток</p><p className={`mt-2 text-xl font-bold tracking-tight ${balance >= 0 ? "text-[#514be0]" : "text-[#c43232]"}`}>{money(balance)}</p></article><article className="rounded-2xl border border-[#f0e2b8] bg-gradient-to-br from-[#fffbed] to-white p-4"><p className="text-xs font-medium text-[#927638]">Норма сбережений</p><p className="mt-2 text-xl font-bold tracking-tight text-[#aa7a10]">{savingsRate}%</p><p className="mt-1 text-[10px] text-[#a18b5d]">в среднем {money(expenses / elapsedDays)} расходов в день</p></article></div>

    <div className="mt-5 grid gap-4 lg:grid-cols-[1.45fr_1fr]">
      <section className="rounded-2xl border border-[#e1e2eb] bg-white p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-[#333548]">Движение денег</h2><p className="mt-1 text-[11px] text-[#828496]">Доходы и расходы · {rangeNames[range].toLowerCase()}</p></div><div className="flex gap-3 text-[10px] font-medium text-[#737588]"><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-sm bg-[#35b779]"/>Доходы</span><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-sm bg-[#f07b62]"/>Расходы</span></div></div>
        <div className="mt-5 grid h-44 items-end gap-1.5 border-b border-[#e9e9f0] pb-2" style={{ gridTemplateColumns: `repeat(${chartValues.length}, minmax(0, 1fr))` }}>{chartValues.map((bucket) => <div key={bucket.start} title={`${bucket.label}: доходы ${money(bucket.income)}, расходы ${money(bucket.expense)}`} className="flex h-full min-w-0 items-end justify-center gap-0.5">{type !== "expense" && <span className="w-2/5 max-w-4 rounded-t-md bg-gradient-to-t from-[#18a765] to-[#70d39c] transition-all" style={{ height: `${bucket.income ? Math.max(5, bucket.income / chartMax * 100) : 0}%` }}/ >}{type !== "income" && <span className="w-2/5 max-w-4 rounded-t-md bg-gradient-to-t from-[#e75f48] to-[#ffab91] transition-all" style={{ height: `${bucket.expense ? Math.max(5, bucket.expense / chartMax * 100) : 0}%` }}/>}</div>)}</div>
        <div className="mt-2 grid gap-1.5 text-center text-[9px] font-medium text-[#818395]" style={{ gridTemplateColumns: `repeat(${chartValues.length}, minmax(0, 1fr))` }}>{chartValues.map((bucket) => <span key={bucket.start} className="truncate">{bucket.label}</span>)}</div>
      </section>
      <section className="rounded-2xl border border-[#e1e2eb] bg-white p-4 sm:p-5"><div className="flex items-start justify-between gap-2"><div><h2 className="text-sm font-bold text-[#333548]">Расходы по категориям</h2><p className="mt-1 text-[11px] text-[#828496]">Всего {money(periodEntries.filter((entry) => entry.type === "expense").reduce((sum, entry) => sum + Number(entry.amount), 0))}</p></div><span className="rounded-lg bg-[#fff2ed] px-2 py-1 text-[10px] font-semibold text-[#c94f39]">{expenseGroups.size} катег.</span></div>
        {expenseBreakdown.length ? <div className="mt-4 space-y-3">{expenseBreakdown.map((item) => { const total = periodEntries.filter((entry) => entry.type === "expense").reduce((sum, entry) => sum + Number(entry.amount), 0); const percent = total ? Math.round(item.amount / total * 100) : 0; return <div key={item.name}><div className="mb-1 flex items-center justify-between gap-2 text-[11px]"><span className="flex min-w-0 items-center gap-2 truncate font-medium text-[#4a4c60]"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ backgroundColor: item.color }}/>{item.name}</span><span className="shrink-0 font-semibold text-[#55576b]">{money(item.amount)} <span className="font-normal text-[#9395a4]">{percent}%</span></span></div><div className="h-2 overflow-hidden rounded-full bg-[#eff0f5]"><div className="h-full rounded-full transition-all" style={{ width: `${percent}%`, backgroundColor: item.color }}/></div></div>; })}</div> : <p className="mt-6 rounded-xl bg-[#fafafd] px-3 py-8 text-center text-xs text-[#85879a]">Расходов за этот период пока нет.</p>}
      </section>
    </div>

    <section className="mt-5 overflow-hidden rounded-2xl border border-[#e1e2eb] bg-white"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#ececf2] px-4 py-4 sm:px-5"><div><h2 className="text-sm font-bold text-[#333548]">Операции</h2><p className="mt-1 text-[10px] text-[#85879a]">{rangeNames[range]} · {filteredEntries.length} записей{filteredEntries.length > 40 ? ", показаны последние 40" : ""}</p></div></div>{recentEntries.length ? recentEntries.map((entry) => { const category = categories.find((item) => item.type === entry.type && item.name === entry.category); return <article key={entry.id} className="flex items-center gap-3 border-b border-[#f0f0f4] px-4 py-3.5 last:border-0 sm:px-5"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${entry.type === "income" ? "bg-[#e8f8ee] text-[#16824b]" : "bg-[#fff0ec] text-[#c94f39]"}`}>{entry.type === "income" ? <ArrowDownLeft aria-hidden="true" size={17}/> : <ArrowUpRight aria-hidden="true" size={17}/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold text-[#393b4f]">{entry.category}</p><span className="rounded-full px-2 py-0.5 text-[9px] font-medium" style={{ color: category?.color ?? "#737588", backgroundColor: category ? `${category.color}18` : "#f1f1f4" }}>{entry.type === "income" ? "Доход" : "Расход"}</span></div><p className="mt-1 truncate text-[10px] text-[#888a9a]">{new Date(`${entry.occurredAt}T12:00:00`).toLocaleDateString("ru-RU", { day: "numeric", month: "long", year: "numeric" })}{entry.description ? ` · ${entry.description}` : ""}</p></div><strong className={`shrink-0 text-xs tabular-nums ${entry.type === "income" ? "text-[#16824b]" : "text-[#c94f39]"}`}>{entry.type === "income" ? "+" : "−"}{money(Number(entry.amount))}</strong><ConfirmAction title="Удалить операцию" description="Операция будет удалена из финансовой истории." action={deleteTransaction} fields={{ id: entry.id }}/></article>; }) : <div className="px-5 py-12 text-center"><p className="text-sm font-semibold text-[#55576b]">Нет операций за выбранный период</p><p className="mt-1 text-xs text-[#85879a]">Добавьте доход или расход, чтобы увидеть аналитику.</p></div>}</section>

    <section className="mt-5 rounded-2xl border border-[#e1e2eb] bg-white p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-bold text-[#333548]">Категории</h2><p className="mt-1 text-[11px] text-[#828496]">Категории доступны при добавлении доходов и расходов.</p></div><Modal title="Новая категория" description="Создайте категорию и задайте ей цвет." trigger={<><Plus aria-hidden="true" size={15}/><span>Новая категория</span></>}><form action={createFinancialCategory} className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-[#525466]">Название<input required maxLength={80} name="name" placeholder="Например, Кафе" className="mt-2 block w-full rounded-xl border border-[#e1e3ec] px-3 py-2.5 text-sm font-normal"/></label><label className="text-xs font-semibold text-[#525466]">Тип<CustomSelect name="type" className="mt-2" options={[{ value: "expense", label: "Расход" }, { value: "income", label: "Доход" }]}/></label><label className="text-xs font-semibold text-[#525466]">Цвет<input type="color" name="color" defaultValue="#f97316" className="mt-2 block h-10 w-16 cursor-pointer rounded-lg border border-[#e1e3ec] bg-white p-1"/></label><button className="self-end rounded-xl bg-[#625cf0] px-4 py-2.5 text-xs font-semibold text-white">Создать</button></form></Modal></div>
      {errorMessage && <p role="alert" className="mt-3 text-xs font-medium text-red-600">{errorMessage}</p>}{params.created && <p className="mt-3 text-xs text-emerald-700">Операция сохранена.</p>}{params.categoryCreated && <p className="mt-3 text-xs text-emerald-700">Категория создана.</p>}{params.categoryUpdated && <p className="mt-3 text-xs text-emerald-700">Категория обновлена.</p>}{params.categoryDeleted && <p className="mt-3 text-xs text-emerald-700">Категория удалена. История операций сохранена.</p>}
      <div className="mt-4 grid gap-2 sm:grid-cols-2">{(["expense", "income"] as const).map((categoryType) => <div key={categoryType} className="rounded-xl bg-[#f8f8fc] p-3"><p className="mb-2 text-[10px] font-bold uppercase tracking-wide text-[#85879a]">{categoryType === "expense" ? "Расходы" : "Доходы"}</p><div className="flex flex-wrap gap-2">{categories.filter((category) => category.type === categoryType).map((category) => <div key={category.id} className="flex items-center gap-2 rounded-full border border-[#e2e3ec] bg-white py-1 pl-2.5 pr-1"><i className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: category.color }}/><span className="text-[10px] font-medium text-[#55576b]">{category.name}</span><Modal title="Изменить категорию" description="Переименование обновит категорию и в старых операциях." trigger={<Pencil aria-hidden="true" size={13}/>} triggerClassName="grid h-6 w-6 place-items-center rounded-full text-[10px] text-[#7b7d8f] transition hover:bg-[#f0efff] hover:text-[#514be0]"><form action={updateFinancialCategory} className="grid gap-3"><input type="hidden" name="id" value={category.id}/><label className="text-xs font-semibold text-[#525466]">Название<input required maxLength={80} name="name" defaultValue={category.name} className="mt-2 block w-full rounded-xl border border-[#e1e3ec] px-3 py-2.5 text-sm font-normal"/></label><label className="text-xs font-semibold text-[#525466]">Цвет<input type="color" name="color" defaultValue={category.color} className="mt-2 block h-10 w-16 cursor-pointer rounded-lg border border-[#e1e3ec] bg-white p-1"/></label><button className="rounded-xl bg-[#625cf0] px-4 py-2.5 text-xs font-semibold text-white">Сохранить</button></form></Modal><ConfirmAction title="Удалить категорию" description="Категория исчезнет из списка выбора. Уже записанные операции останутся в истории." action={deleteFinancialCategory} fields={{ id: category.id }}/></div>)}</div></div>)}</div>
    </section>
  </ModuleShell>;
}
